---
title: "lista_2"
output: html_document
---

## Dados para Kaplan-Meier

```{r setup, message=FALSE, warning=FALSE}
library(survival)
```

```{r}
dados <- read.csv("dados_lista_2_ex3.csv")

dados$recaida <- as.integer(dados$recaida)

# sexo do paciente
dados$sexo <- factor(dados$sexo, levels = c(0, 1), labels = c("Masculino", "Feminino"))

# Os dois diferentes grupos de comparação - remédio ou não
dados$tto <- factor(dados$tto, levels = c(0, 1), labels = c("Controle", "Tratamento"))

dados
summary(dados)
```

`recaida = 1` indica evento e `recaida = 0` indica censura.

## Curva de Kaplan-Meier geral

```{r}
ajuste_geral <- survfit(Surv(tempo, recaida) ~ 1, data = dados)

plot(
  ajuste_geral,
  xlab = "Tempo",
  ylab = "Probabilidade de sobreviver sem recaida",
  main = "Kaplan-Meier geral",
  lwd = 2,
  mark.time = TRUE
)

summary(ajuste_geral)
```

## Curvas por tratamento

```{r}
ajuste_tto <- survfit(Surv(tempo, recaida) ~ tto, data = dados)

plot(
  ajuste_tto,
  col = c("firebrick", "steelblue"),
  lwd = 2,
  xlab = "Tempo",
  ylab = "Probabilidade de sobreviver sem recaida",
  main = "Kaplan-Meier por tratamento",
  mark.time = TRUE
)

legend(
  "topright",
  legend = levels(dados$tto),
  col = c("firebrick", "steelblue"),
  lwd = 2,
  bty = "n"
)

summary(ajuste_tto)
survdiff(Surv(tempo, recaida) ~ tto, data = dados)
```

## Curvas por sexo

```{r}
ajuste_sexo <- survfit(Surv(tempo, recaida) ~ sexo, data = dados)

plot(
  ajuste_sexo,
  col = c("darkgreen", "goldenrod"),
  lwd = 2,
  xlab = "Tempo",
  ylab = "Probabilidade de sobreviver sem recaida",
  main = "Kaplan-Meier por sexo",
  mark.time = TRUE
)

legend(
  "topright",
  legend = levels(dados$sexo),
  col = c("darkgreen", "goldenrod"),
  lwd = 2,
  bty = "n"
)

summary(ajuste_sexo)
survdiff(Surv(tempo, recaida) ~ sexo, data = dados)
```

## Modelo com covariaveis

```{r}
modelo_cox <- coxph(Surv(tempo, recaida) ~ sexo + logWBC + tto, data = dados)

summary(modelo_cox)
```

\`\`\`
