---
title: "q8_lista1"
output: html_document
---

# Questão 8

S(t + y) \<= S(t) + S(y) -\> NBU (new better than used)

S(t + y) \>= S(t) + S(y) -\> NWU (new worse than used)

```{r}
set.seed(123)
```

```{r}
# Letra A 
# T é uniforme [0, 3]
# NBU ou NWU?

x <- sort(runif(100, min = 0, max = 3))
y <- sort(runif(100, min = 0, max = 3 - x))

Igual <- 0
NWU <- 0
NBU <- 0

letra_a_parte_a <- numeric(100)
letra_a_parte_b <- numeric(100)

# F(t) é integral de 1/3
# F(T) dá t/3
# S(t) = 1 - F(t)

sobrevivencia_letraA <- function(x) {
  
    if((x >= 0) || (x <= 3)){
        valor = 1 - (x/3)
    }
    if(x>3){
        valor = 0
    }
    if(x<0){
        valor = 1
    }

    return(valor)
}


for (i in 1:100) {
    
    t1 <- x[i]
    t2 <- y[i]
    
    a <- sobrevivencia_letraA(t1 + t2)
    b <- sobrevivencia_letraA(t1) * sobrevivencia_letraA(t2)
    
    letra_a_parte_a[i] <- a
    letra_a_parte_b[i] <- b
    
    if(a < b){
        NBU <- NBU + 1 
    }
    if(a > b){
        NWU <- NWU + 1
    }
    if(a == b){
        Igual <- Igual + 1
    }
}

print(NBU)
print(NWU)
print(Igual)
```

```{r}

a <- sobrevivencia_letraA(1 + 2)
b <- sobrevivencia_letraA(1) * sobrevivencia_letraA(2)
print(a)
print(b)
print("----------------------------")
a <- sobrevivencia_letraA(1 + 0)
b <- sobrevivencia_letraA(1) * sobrevivencia_letraA(0)
print(a)
print(b)
print("----------------------------")
a <- sobrevivencia_letraA(1.5 + 0.5)
b <- sobrevivencia_letraA(1.5) * sobrevivencia_letraA(0.5)
print(a)
print(b)
print("----------------------------")
```

```{r}
plot(
  letra_a_parte_a, letra_a_parte_b 
)
abline(a = 0, b = 1, col = "red", lwd = 2)
```

## Resposta Letra A - NBU

------------------------------------------------------------------------

```{r}
# Letra B 
# f(t) = t/2 se 0<t<2
# NBU ou NWU?

x <- sort(runif(100, min = 0, max = 2))
y <- sort(runif(100, min = 0, max = 2 - x))

Igual <- 0
NWU <- 0
NBU <- 0

letra_b_parte_a <- numeric(100)
letra_b_parte_b <- numeric(100)

# F(t) é integral de t/2
# F(t) dá t^2/4
# S(t) = 1 - F(t) entre 0 e 2

sobrevivencia_letraB <- function(x) {
  
    if((x >= 0) || (x <= 2)){
        valor = (x*x/4)
    }
    if(x>2){
        valor = 0
    }
    if(x<0){
        valor = 1
    }

    return(valor)
}

for (i in 1:100) {
    
    t1 <- x[i]
    t2 <- y[i]
    
    a <- sobrevivencia_letraB(t1 + t2)
    b <- sobrevivencia_letraB(t1) * sobrevivencia_letraB(t2)
    
    letra_b_parte_a[i] <- a
    letra_b_parte_b[i] <- b
    
    if(a < b){
        NBU <- NBU + 1 
    }
    if(a > b){
        NWU <- NWU + 1
    }
    if(a == b){
        Igual <- Igual + 1
    }
}

print(NBU)
print(NWU)
print(Igual)
```

```{r}

a <- sobrevivencia_letraB(1 + 0.5)
b <- sobrevivencia_letraB(1) * sobrevivencia_letraB(0.5)
print(a)
print(b)
print("----------------------------")

a <- sobrevivencia_letraB(1 + 1)
b <- sobrevivencia_letraB(1) * sobrevivencia_letraB(1)
print(a)
print(b)
print("----------------------------")

a <- sobrevivencia_letraB(0.5 + 0.5)
b <- sobrevivencia_letraB(0.5) * sobrevivencia_letraB(0.5)
print(a)
print(b)
print("----------------------------")
```

```{r}
plot(
  letra_b_parte_a, letra_b_parte_b 
)
abline(a = 0, b = 1, col = "red", lwd = 2)
```

## Resposta Letra B - NBU

```{r}
# Letra C
# f(t) = 1 - t/2 se 0<t<2
# NBU ou NWU?

x <- sort(runif(100, min = 0, max = 2))
y <- sort(runif(100, min = 0, max = 2 - x))

Igual <- 0
NWU <- 0
NBU <- 0

letra_c_parte_a <- numeric(100)
letra_c_parte_b <- numeric(100)

# F(t) é integral de t/2
# F(t) dá t - t^2/4
# S(t) = 1 - F(t) entre 0 e 2

sobrevivencia_letraC <- function(x) {
  
    if((x >= 0) || (x <= 2)){
        valor = (x - (x*x/4))
    }
    if(x>2){
        valor = 0
    }
    if(x<0){
        valor = 1
    }

    return(valor)
}

for (i in 1:100) {
    
    t1 <- x[i]
    t2 <- y[i]
    
    a <- sobrevivencia_letraC(t1 + t2)
    b <- sobrevivencia_letraC(t1) * sobrevivencia_letraC(t2)
    
    letra_c_parte_a[i] <- a
    letra_c_parte_b[i] <- b
    
    if(a < b){
        NBU <- NBU + 1 
    }
    if(a > b){
        NWU <- NWU + 1
    }
    if(a == b){
        Igual <- Igual + 1
    }
}

print(NBU)
print(NWU)
print(Igual)
```

```{r}

a <- sobrevivencia_letraC(1 + 0.5)
b <- sobrevivencia_letraC(1) * sobrevivencia_letraC(0.5)
print(a)
print(b)
print("----------------------------")
```

```{r}

plot(
  letra_c_parte_a, letra_c_parte_b 
)
abline(a = 0, b = 1, col = "red", lwd = 2)
```

## Resposta Letra B - NBU
